root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "npm run build:css && templ generate && go build -o ./tmp/main cmd/main.go"
  # cmd = "templ generate && tailwindcss -i assets/css/tailwind.css -o static/css/tailwind.css --minify && go build -o ./tmp/main cmd/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "css", "env"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
